language: objective-c
osx_image: xcode61
rvm:
- 2.1.2
install:
- ./Scripts/install.sh
script:
- ./Scripts/build.sh
deploy:
  provider: releases
  api_key:
    secure: WaaDBGs4Ps8H0rARwG85yx4n0gX8vW1Npp199afHwqyOkZkMOfiguX6vGAOXCRQlHNcKymdOYiN8gRXKPUuMVWO91Mo5VnT75C/fJBFP41LRvTtSb0SyJTSjbi24kqWIp7bo28Q5U9cHEH1J0W8wN5kjgNDorrNjyfK93FF0mVaWb43sMTUhh/5Yz/0IDi6jl+ndT1f4yMAt32q9g=
  upload-dir: ci-build
  on:
    repo: OpenHogwarts/hogwarts
